config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users

  get 'user_root', controller: :users, action: :after_edit, method: :get

  namespace :users do
    get :sign_out
  end

  resources :blog_contents, path: :blog, as: :blog, param: :slug, only: [:create, :edit, :destroy]

  scope ':name' do
    get '/', controller: :users, action: :show
    resources :blog_contents, path: :blog, as: :blog, param: :slug, only: [:index, :show]
  end
end

app/models/blog_content.rb
class BlogContent < ActiveRecord::Base
  def to_param
    slug
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  include Renderable

  validates(:name,
            presence: true,
            format: /\A[a-zA-Z0-9_\-]+\Z/,
            uniqueness: true,
            length: { minimum: 3, maximum: 240 },
            username_not_reserved: true
           )
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  PERMITED_COLUMNS_FOR_USER = [
    :name,
    :member_number,
    :screen_name,
    :screen_name_kana,
    :nick,
    :profile,
  ]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    PERMITED_COLUMNS_FOR_USER.each do |column|
      devise_parameter_sanitizer.for(:sign_up) << column
      devise_parameter_sanitizer.for(:sign_in) << column
      devise_parameter_sanitizer.for(:account_update) << column
    end
  end

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_contents_controller.rb
class BlogContentsController < ApplicationController
  before_action :set_user
  before_action :set_blog_content, only: [:show, :edit, :update, :destroy]

  # GET /blog_contents
  def index
    @blog_contents = BlogContent.all
  end

  # GET /blog_contents/1
  def show
  end

  # GET /blog_contents/new
  def new
    @blog_content = BlogContent.new
  end

  # GET /blog_contents/1/edit
  def edit
  end

  # POST /blog_contents
  def create
    @blog_content = BlogContent.new(blog_content_params)

    if @blog_content.save
      redirect_to @blog_content, notice: 'Blog content was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /blog_contents/1
  def update
    if @blog_content.update(blog_content_params)
      redirect_to @blog_content, notice: 'Blog content was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /blog_contents/1
  def destroy
    @blog_content.destroy
    redirect_to blog_contents_url, notice: 'Blog content was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog_content
    @blog_content = BlogContent.find(params[:id])
  end

  def set_user
    @user = User.find_by(name: params[:name]) || raise(Neecomi::Err::NotFound)
  end

  # Only allow a trusted parameter "white list" through.
  def blog_content_params
    params.require(:blog_content).permit(
      :user_id,
      :title,
      :body,
      :published_at
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :after_edit]

  def sign_out
    if user_signed_in?
      render 'devise/sessions/sign_out'
    else
      redirect_to :root
    end
  end

  def show
    @user = current_user
  end

  def after_edit
    redirect_to "/#{current_user.name}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_contents_helper.rb
module BlogContentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blog_contents/_form.html.slim
= form_for @blog_content do |f|
  - if @blog_content.errors.any?
    #error_explanation
      h2 = "#{pluralize(@blog_content.errors.count, "error")} prohibited this blog_content from being saved:"
      ul
        - @blog_content.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .actions = f.submit 'Save'

app/views/blog_contents/edit.html.slim
h1 Editing blog_content

== render 'form'

= link_to 'Show', @blog_content
'|
= link_to 'Back', blog_contents_path

app/views/blog_contents/index.html.slim
h1 #{@user.name}'s blog

div
  - if @blog_contents.empty?
    | 投稿はありません
  - else
    - @blog_contents.each do |blog|
      h2
        blog_contents.title
      div
        blog_contents.body

app/views/blog_contents/new.html.slim
h1 New blog_content

== render 'form'

= link_to 'Back', blog_contents_path

app/views/blog_contents/show.html.slim
p#notice = notice

p
  strong User:
  = @blog_content.user_id
p
  strong Title:
  = @blog_content.title
p
  strong Body:
  = @blog_content.body
p
  strong Published at:
  = @blog_content.published_at
p
  strong Datetime:
  = @blog_content.datetime

= link_to 'Edit', edit_blog_content_path(@blog_content)
'|
= link_to 'Back', blog_contents_path

app/views/home/index.html.slim
h1 Home#index
p Find me in app/views/home/index.html.slim

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Neecomi
    = csrf_meta_tags
    = yield :header
  body
    div class="flash_message"
      p class="notice"
        = notice
      p class="alert"
        = alert
    = yield

app/views/users/_form.html.slim
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      h2
        = pluralize(@user.errors.count, "error")
        |  prohibited this user from being saved:
      ul
        - @user.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :name
    br
    = f.text_field :name
  .field
    = f.label :email
    br
    = f.text_field :email
  .field
    = f.label :member_number
    br
    = f.text_field :member_number
  .field
    = f.label :screen_name
    br
    = f.text_field :screen_name
  .field
    = f.label :screen_name_kana
    br
    = f.text_field :screen_name_kana
  .field
    = f.label :nick
    br
    = f.text_field :nick
  .field
    = f.label :profile
    br
    = f.text_area :profile
  .field
    = f.label :password
    br
    = f.password_field :password
  .field
    = f.label :password_confirmation
    br
    = f.password_field :password_confirmation
  .actions
    = f.submit

app/views/users/edit.html.slim
h1
  | Editing user
= render 'form'
= link_to 'Show', @user
|  | 
= link_to 'Back', users_path

app/views/users/index.html.slim
h1
  | Listing users
table
  thead
    tr
      th
        | Name
      th
        | Email
      th
        | Member Number
      th
        | Screen Name
      th
        | Screen Name kana
      th
        | Nick
      th
        | Profile
      th[colspan="3"]
  tbody
    - @users.each do |user|
      tr
        td
          = user.name
        td
          = user.email
        td
          = user.member_number
        td
          = user.screen_name
        td
          = user.screen_name_kana
        td
          = user.nick
        td
          = user.profile
        td
          = link_to 'Show', user
        td
          = link_to 'Edit', edit_user_path(user)
        td
          = link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1
  | New user
= render 'form'
= link_to 'Back', users_path

app/views/users/show.html.slim
= content_for :header do
  meta name='viewport' content='width=device-width, initial-scale=1.0'
  = stylesheet_link_tag 'http://yui.yahooapis.com/pure//grids-responsive.css'
  = stylesheet_link_tag 'users'

div id='layout' class='pure-g'
  div class='sidebar pure-u-1 pure-u-md-1-4'
    div class='header'
      div
        img class='gravatar_icon' src=%'http://gravatar.com/avatar/#{Digest::MD5.hexdigest(@user.email)}'
      h1 class='brand-title'
        = @user.name
      h2 class='brand-tagline'
        = @user.screen_name
      nav class='nav'
        ul class='nav-list'
          li class='nav-item'
            = @user.email
  div class='content pure-u-1 pure-u-md-3-4'
    div
      div class='posts'
        h1 class='content-subhead'
          | content-subhead
        section class='post'
          header class='post-header'
            h2 class='post-title'
              | post-title
            p class='post-meta'
          div class='post-description'
            p#notice
              = notice
            p
              strong
                | Name:
              = @user.name
            p
              strong
                | Email:
              = @user.email
            p
              strong
                | Member number:
              = @user.member_number
            p
              strong
                | Screen Name:
              = @user.screen_name
            p
              strong
                | Screen Name kana:
              = @user.screen_name_kana
            p
              strong
                | Nick
              = @user.nick
            p
              strong
                | Profile
            p
              = @user.render(:profile).html_safe
            = link_to 'Edit', edit_user_registration_path
            |  | 
            = link_to 'Back', :root